packages:
  - 'examples/**/*'
  - 'packages/*'
catalog:
  '@tanstack/react-devtools': ^0.1.1
  '@tanstack/react-query': ^5.83.0
  '@tanstack/react-query-devtools': ^5.83.0
  '@tanstack/react-router': ^1.130.2
  '@tanstack/react-router-devtools': ^1.130.2
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.2
  '@vitejs/plugin-react': ^4.4.1
  react: ^19.1.0
  react-dom: ^19.1.0
  vite: ^7.0.6
