packages:
  - 'examples/**/*'
  - 'packages/*'
catalog:
  '@tanstack/react-devtools': ^0.7.0
  '@tanstack/react-query': ^5.90.1
  '@tanstack/react-query-devtools': ^5.90.1
  '@tanstack/react-router': ^1.131.50
  '@tanstack/react-router-devtools': ^1.131.50
  '@types/react': ^19.1.13
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^4.7.0
  react: ^19.1.1
  react-dom: ^19.1.1
  vite: ^7.1.7
