packages:
  - 'examples/**/*'
  - 'packages/*'

catalog:
  '@prisma/client': ^6.13.0
  '@prisma/extension-accelerate': ^2.0.2
  '@prisma/studio-core': ^0.5.1
  '@types/node': ^22.15.2
  '@types/ws': ^8.18.1
  '@testing-library/dom': '^10.4.0'
  '@testing-library/react': '^16.2.0'
  clsx: ^2.1.1
  goober: ^2.1.16
  jsdom: ^26.1.0
  prisma: ^6.13.0
  tailwindcss: ^4.0.6
  typescript: 5.8.3
  web-vitals: ^4.2.4
  ws: ^8.18.3

catalogs:
  vite:
    '@tailwindcss/vite': ^4.0.6
    '@vitejs/plugin-react': ^4.4.1
    vite-plugin-solid: ^2.11.6
    vite: ^7.0.6
    vite-tsconfig-paths: ^5.1.4
    vitest: ^3.1.2

  react:
    '@testing-library/dom': ^10.4.0
    '@testing-library/react': ^16.2.0
    '@types/react': ^19.1.2
    '@types/react-dom': ^19.1.2
    react: ^19.1.0
    react-dom: ^19.1.0

  solid:
    '@solid-primitives/keyboard': ^1.2.8
    solid-js: ^1.9.7

  tanstack:
    '@tanstack/devtools': ^0.2.1
    '@tanstack/devtools-event-bus': ^0.2.1
    '@tanstack/devtools-event-client': ^0.2.1
    '@tanstack/react-devtools': ^0.1.1
    '@tanstack/react-query': ^5.83.0
    '@tanstack/react-query-devtools': ^5.83.0
    '@tanstack/react-router': ^1.130.2
    '@tanstack/react-router-devtools': ^1.130.2
    '@tanstack/react-router-with-query': ^1.130.2
    '@tanstack/react-start': ^1.130.15
    '@tanstack/router-plugin': ^1.121.2
    '@tanstack/solid-devtools': ^0.2.1
    '@tanstack/solid-query': ^5.83.0
    '@tanstack/solid-query-devtools': ^5.83.0
    '@tanstack/solid-router': ^1.129.8
    '@tanstack/solid-router-devtools': ^1.129.8
