/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmitServerPingRouteImport } from './routes/emit-server-ping'
import { Route as IndexRouteImport } from './routes/index'

const EmitServerPingRoute = EmitServerPingRouteImport.update({
  id: '/emit-server-ping',
  path: '/emit-server-ping',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/emit-server-ping': typeof EmitServerPingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/emit-server-ping': typeof EmitServerPingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/emit-server-ping': typeof EmitServerPingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/emit-server-ping'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/emit-server-ping'
  id: '__root__' | '/' | '/emit-server-ping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmitServerPingRoute: typeof EmitServerPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/emit-server-ping': {
      id: '/emit-server-ping'
      path: '/emit-server-ping'
      fullPath: '/emit-server-ping'
      preLoaderRoute: typeof EmitServerPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmitServerPingRoute: EmitServerPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
